{% set name = "qcelemental" %}
{% set version = "0.50b1" %}
{% set sha256 = "bf634ee652e7d95e906e291989513224233b1d705c26afeac86e451f316b3c04" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.8
    - pip
    - packaging
  run:
    - numpy
    - pint
    - pydantic >=2.0
    - python >=3.8
]

test:
  imports:
    - qcelemental
  requires:
    # - networkx >=2.4.0          # these might be imposing a pyqt dependence on qcel for the c-f migrators
    # - nglview                   # ditto
    - pytest
    - scipy
  commands:
    - pytest --pyargs qcelemental -k "not pubchem_multiout_g"
    - pip check
    - python -c "import qcelemental as qc;assert qc.__version__ == '{{ version }}', f'{qc.__version__=} differs from recipe=\'{{ version }}\''"

about:
  home: https://github.com/MolSSI/QCElemental
  dev_url: https://github.com/MolSSI/QCElemental
  doc_url: https://molssi.github.io/QCElemental/
  doc_source_url: https://github.com/MolSSI/QCElemental/blob/master/docs/source/index.rst
  license: BSD-3-Clause
  license_url: https://opensource.org/licenses/BSD-3-Clause
  license_file: LICENSE
  license_family: BSD
  summary: QCElemental is a resource module for quantum chemistry containing physical constants and periodic table data from NIST and molecule handlers.

extra:
  recipe-maintainers:
    - loriab
    - dgasmith
    - lnaden
    - bennybp
